language: rust

cache: cargo

addons:
    apt:
        update: true

before_script:
    - sudo apt install lxc-dev libclang-dev

script:
    - cargo test --features=v2_0
    - cargo test --features=v2_0 --release
