[package]
name = "lxc"
version = "0.1.0"
authors = ["Sanpi <sanpi@homecomputing.fr>"]
repository = "https://github.com/sanpii/lxc-rs.git"
documentation = "https://docs.rs/lxc"
keywords = ["lxc"]
license = "MIT"
categories = ["api-bindings"]
description = "Linux Containers API"

[dependencies]
bitflags = "1.0"

[dependencies.lxc-sys]
version = "0.1"
path = "./lxc-sys"

[badges]
travis-ci = { repository = "sanpii/lxc-rs" }
gitlab = { repository = "sanpi/lxc-rs" }
